package es.uniovi.raul.roster.cli;

import java.util.*;

public class CommandLine {
    public static final String GROUP_FILE_FLAG = "-g";
    public static final String OUTPUT_FILE_FLAG = "-r";
    public static final String EXCEL_FILE = "xls";

    public static Map<String, String> getCommandLineArguments(String[] args) {

        Map<String, String> map = new HashMap<>();
        int i = 0;
        while (i < args.length) {
            if (args[i].equals(OUTPUT_FILE_FLAG) && i + 1 < args.length)
                map.put(OUTPUT_FILE_FLAG, args[++i]);
            else if (args[i].equals(GROUP_FILE_FLAG) && i + 1 < args.length)
                map.put(GROUP_FILE_FLAG, args[++i]);
            else if (args[i].endsWith(".xls"))
                map.put(EXCEL_FILE, args[i]);
            else if (args[i].equals("-h") || args[i].equals("--help"))
                map.put("-h", "");
            i++;
        }

        if (!map.containsKey("xls"))
            map.put("xls", "alumnosMatriculados.xls");

        if (!map.containsKey(OUTPUT_FILE_FLAG))
            map.put(OUTPUT_FILE_FLAG, "roster.txt");

        if (!map.containsKey(GROUP_FILE_FLAG))
            map.put(GROUP_FILE_FLAG, "groups.csv");

        return map;
    }

    public static void printError(String message) {
        System.err.println("\n\n --> Error!!! " + message + "\n");
    }

    public static void printHelp() {
        System.out.println(
                """
                        Roster Generator for Github Classroom.

                        Reads an Excel file with students generated by SIES (https://sies.uniovi.es/serviciosdocentes),
                        and generates a roster file with the students ids, optionally filtered by groups. The content of
                        this generated file is the text that must be copy and pasted in the Github Classroom roster field.

                        See 'https://github.com/raul-izquierdo/create_roster' for more information.

                        Usage: java -jar roster.jar [<sies.xls>] [-g <groups.csv>] [-o <output_file>]

                        Options:
                          <sies.xls>        The Excel file from SIES with the students in the subject.
                                            (default = "alumnosMatriculados.xls").
                          -g <groups_file>  The file containing the groups of the teacher. Only the students
                                            in these groups will be included in the roster. If not specified,
                                            all students will be included.
                                            (default = "groups.csv").
                          -r <output.txt>   The file name for the generated roster.
                                            (default = "roster.txt").
                          -h, --help        Show this help message.

                        """);

        printGroupsFormat();
        printCredits();

    }

    public static void printGroupsFormat() {
        System.out.println(
                """
                        About "groups.csv":

                        - It should contain the ids of the groups, one line per group.
                          Example:
                            01
                            02
                            i02
                            08

                        - It is recommended to use the same "groups.csv" as in "show_solutions".
                          Although that file is a csv file with more columns, only the first column will
                          be used (the group_id).
                        """);
    }

    public static void printCredits() {
        System.out.println("""

                Escuela de Ingenieria Informatica. Universidad de Oviedo.
                Raúl Izquierdo Castanedo (raul@uniovi.es)
                """);
    }
}
